module.exports = {
  DISPLAY_WAITING: "DISPLAY_WAITING",
  DISPLAY_GAME: "DISPLAY_GAME",
  DISPLAY_WAITING_TO_START: "DISPLAY_WAITING_TO_START",
  DISPLAY_GAME_OVER: "DISPLAY_GAME_OVER",
  CONTROLLER_GAME_OFFLINE: "CONTROLLER_GAME_OFFLINE",
  CONTROLLER_JOIN: "CONTROLLER_JOIN",
  CONTROLLER_IN_QUEUE: "CONTROLLER_IN_QUEUE",
  CONTROLLER_START: "CONTROLLER_START",
  CONTROLLER_GAME_CONTROLS: "CONTROLLER_GAME_CONTROLS",
  CONTROLLER_GAME_OVER: "CONTROLLER_GAME_OVER"
}
