export const commands = {
  COMMAND_LEFT: "COMMAND_LEFT",
  COMMAND_RIGHT: "COMMAND_RIGHT",
  COMMAND_DOWN: "COMMAND_DOWN",
  COMMAND_DROP: "COMMAND_DROP",
  COMMAND_ROTATE: "COMMAND_ROTATE",
  COMMAND_START: "COMMAND_START",
  COMMAND_GAME_OVER: "COMMAND_GAME_OVER",
  COMMAND_CONTROLLER_JOIN: "COMMAND_CONTROLLER_JOIN",
  COMMAND_DISPLAY_JOIN: "COMMAND_DISPLAY_JOIN",
}
